{% set name = "api-inference-community" %}
{% set version = "0.0.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/api_inference_community-{{ version }}.tar.gz
  sha256: de50e5f9ab0256c2d80b5cbd1f4dfca0d4d0329019692351d33fe73f69084829

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - datasets >=2.2
    - huggingface_hub >=0.5.1
    - numpy >=1.18.0
    - parameterized >=0.8.1
    - pillow >=8.2.0
    - pydantic >=1.8.1
    - python >={{ python_min }}
    - starlette >=0.14.2

test:
  imports:
    - api_inference_community
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/huggingface/api-inference-community
  summary: A package with helper tools to build an API Inference docker app for Hugging Face API inference using huggingface_hub
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - adrinjalali
